version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    environment:
      MIX_ENV: "dev"
      PG_HOST: "db"
      PG_USERNAME: "postgres"
      PG_PASSWORD: "postgres"
      PG_DATABASE: "phoenix_blog_dev"

    command: mix phoenix.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
