# the database image
#db:
#  image: "postgres:9.4"
#  ports:
#    - "5432:5432"
#  environment:
#    POSTGRES_USER: postgres
#    POSTGRES_PASSWORD: postgres
#  volumes_from:
#    - dbdata
db:
  image: postgres
# for persistance of database data
#dbdata:
#  image: "postgres:9.4"
#  volumes:
#    - /var/lib/postgres
#  command: "true"

# the main image, this is the application
web:
  build: .
  environment:
    MIX_ENV: "dev"
    PG_HOST: "db"
    PG_USERNAME: "postgres"
    PG_PASSWORD: "postgres"
    PG_DATABASE: "phoenix_blog_dev"
  ports:
    - "4000:4000"
  links:
    - db
